//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMION
    {
        public int CAMID { get; set; }
        public string CAMCODE { get; set; }
        public string CAMINTITULE { get; set; }
        public Nullable<int> DEPID { get; set; }
        public Nullable<int> DEVICEID { get; set; }
        public Nullable<int> CAMCHAUFFEURID { get; set; }
        public Nullable<int> CAMVENDEURID { get; set; }
        public Nullable<int> DOSID { get; set; }
        public Nullable<int> TIRCAM { get; set; }
        public Nullable<int> CAMISACTIF { get; set; }
        public string CAMMATRICULE { get; set; }
        public Nullable<int> CAMDISPO { get; set; }
        public Nullable<System.DateTime> CAMDATEVIDANGE { get; set; }
        public Nullable<decimal> CAMVOLUME { get; set; }
        public Nullable<decimal> CAMPOIDSSUPP { get; set; }
        public Nullable<System.DateTime> CAMLASTMISSION { get; set; }
        public string CAMMODELE { get; set; }
        public string CAMREFERENCE { get; set; }
        public Nullable<System.DateTime> CAMVISITE { get; set; }
        public Nullable<System.DateTime> CAMVIGNETTE { get; set; }
        public string CAMNOTE { get; set; }
        public string NUMEROTATION_PREFIX { get; set; }
        public string USERUPDATE { get; set; }
        public string USERCREATE { get; set; }
        public Nullable<System.DateTime> DATECREATE { get; set; }
        public Nullable<System.DateTime> DATEUPDATE { get; set; }
        public Nullable<int> PLATEFORME { get; set; }
        public string DISTRIBUTEUR { get; set; }
    }
}
