//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MTEntities : DbContext
    {
        public MTEntities()
            : base("name=MTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ARTICLES> ARTICLES { get; set; }
        public virtual DbSet<CAMION> CAMION { get; set; }
        public virtual DbSet<DOCUMENT> DOCUMENT { get; set; }
        public virtual DbSet<ECHEANCE> ECHEANCE { get; set; }
        public virtual DbSet<REGLEMENT> REGLEMENT { get; set; }
        public virtual DbSet<TIERS> TIERS { get; set; }
    }
}
