//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ECHEANCE
    {
        public int ECHID { get; set; }
        public Nullable<int> DOSID { get; set; }
        public Nullable<int> DOCID { get; set; }
        public Nullable<int> DOMID { get; set; }
        public Nullable<int> TYPDOCID { get; set; }
        public Nullable<System.DateTime> ECHDATE { get; set; }
        public Nullable<int> RGMID { get; set; }
        public Nullable<int> REGTYPE { get; set; }
        public Nullable<decimal> ECHTAUX { get; set; }
        public Nullable<decimal> ECHMONTANT { get; set; }
        public Nullable<decimal> ECHMONTANTREGLE { get; set; }
        public Nullable<decimal> ECHMONTANTSOLDE { get; set; }
        public Nullable<int> ECHISREGLE { get; set; }
        public string USERUPDATE { get; set; }
        public string USERCREATE { get; set; }
        public Nullable<System.DateTime> DATECREATE { get; set; }
        public Nullable<System.DateTime> DATEUPDATE { get; set; }
        public Nullable<int> ECHIDFROMMOBILE { get; set; }
    }
}
