//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGLEMENT
    {
        public int REGID { get; set; }
        public string REGNUM { get; set; }
        public Nullable<int> DOSID { get; set; }
        public Nullable<int> TRNID { get; set; }
        public Nullable<System.DateTime> REGDATE { get; set; }
        public string REGREF { get; set; }
        public string REGLIBELLE { get; set; }
        public Nullable<int> TIRID { get; set; }
        public Nullable<int> TIRPAYID { get; set; }
        public Nullable<decimal> REGMONTANT { get; set; }
        public Nullable<int> DEVID { get; set; }
        public Nullable<decimal> DEVCOURS { get; set; }
        public Nullable<int> RGMID { get; set; }
        public Nullable<int> REGISIMPUTE { get; set; }
        public Nullable<int> REGTYPE { get; set; }
        public Nullable<System.DateTime> REGECHEANCE { get; set; }
        public Nullable<decimal> REGMONTANTIMPUTE { get; set; }
        public Nullable<decimal> REGMONTANTSOLDE { get; set; }
        public Nullable<decimal> REGMONTANTECART { get; set; }
        public string REGNOTE { get; set; }
        public string USERUPDATE { get; set; }
        public string USERCREATE { get; set; }
        public Nullable<System.DateTime> DATECREATE { get; set; }
        public Nullable<System.DateTime> DATEUPDATE { get; set; }
        public Nullable<int> REGIDFROMMOBILE { get; set; }
        public Nullable<int> TTRNID { get; set; }
        public Nullable<int> TIRCAM { get; set; }
        public string CHQNUMERO { get; set; }
        public Nullable<System.DateTime> CHQDATE { get; set; }
        public string CHQBANQUE { get; set; }
        public Nullable<int> REGNAT { get; set; }
        public string DISTRIBUTEUR { get; set; }
    }
}
