//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIERS
    {
        public int TIRID { get; set; }
        public Nullable<int> DOSID { get; set; }
        public Nullable<int> TIRCATID { get; set; }
        public Nullable<int> TIRCATTIERSID { get; set; }
        public string TIRTYPE { get; set; }
        public Nullable<int> TIRISINTERNE { get; set; }
        public string TIRCODE { get; set; }
        public string TIRCODEERP { get; set; }
        public string TIRSOCIETE { get; set; }
        public string TIRABREGE { get; set; }
        public string CPTCODE { get; set; }
        public Nullable<int> COLID { get; set; }
        public Nullable<int> ADRFID { get; set; }
        public Nullable<int> ADRLID { get; set; }
        public Nullable<int> CONTACTID { get; set; }
        public string TIRIDENTIFIANT { get; set; }
        public string TIRCIN { get; set; }
        public Nullable<int> TIRPATENTE { get; set; }
        public string TIRACTIVITE { get; set; }
        public Nullable<int> DEVID { get; set; }
        public Nullable<int> TRFID { get; set; }
        public Nullable<int> TRFPID { get; set; }
        public Nullable<int> RGMID { get; set; }
        public Nullable<int> TVATID { get; set; }
        public Nullable<int> TPFTID { get; set; }
        public Nullable<int> TIRISASSUJETTITVA { get; set; }
        public Nullable<int> TIRISASSUJETTITPF { get; set; }
        public Nullable<int> TIRISFACTURE { get; set; }
        public Nullable<int> TIRISACTIF { get; set; }
        public Nullable<decimal> TIRTAUXREMISE { get; set; }
        public Nullable<decimal> TIRTAUXESCOMPTE { get; set; }
        public Nullable<decimal> TIRPUREMISE { get; set; }
        public Nullable<decimal> TIRENCOURS { get; set; }
        public Nullable<int> TIRNBFACT { get; set; }
        public Nullable<int> STATENUMID1 { get; set; }
        public Nullable<int> STATENUMID2 { get; set; }
        public Nullable<int> STATENUMID3 { get; set; }
        public Nullable<int> STATENUMID4 { get; set; }
        public Nullable<int> STATENUMID5 { get; set; }
        public Nullable<int> STATENUMID6 { get; set; }
        public Nullable<System.DateTime> TIRLASTVISITE { get; set; }
        public string TIRRATE { get; set; }
        public Nullable<decimal> TIRSOLDER { get; set; }
        public Nullable<decimal> TIRSOLDEINI { get; set; }
        public Nullable<int> TIRISCREDIT { get; set; }
        public Nullable<int> TIRSITEINTERNE { get; set; }
        public string TIRAGREMENT { get; set; }
        public Nullable<System.DateTime> TIRDATEAGREMENT { get; set; }
        public Nullable<int> TIRRISQUE { get; set; }
        public Nullable<int> TIRPAYEUR { get; set; }
        public Nullable<int> TIRFACTURE { get; set; }
        public string TIRNOTE { get; set; }
        public string USERCREATE { get; set; }
        public string USERUPDATE { get; set; }
        public Nullable<System.DateTime> DATECREATE { get; set; }
        public Nullable<System.DateTime> DATEUPDATE { get; set; }
        public Nullable<int> TIRIDFROMMOBILE { get; set; }
        public Nullable<decimal> CREDITCONTENTIEUX { get; set; }
        public Nullable<int> CAMID { get; set; }
        public Nullable<int> FLAG_SYNC_ERP { get; set; }
        public string TIRICE { get; set; }
        public string DISTRIBUTEUR { get; set; }
    }
}
