//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZDW_DOCUMENT_VIEW
    {
        public int DOCID { get; set; }
        public string DOCNUM { get; set; }
        public Nullable<int> DOMID { get; set; }
        public Nullable<int> TYPDOCID { get; set; }
        public Nullable<int> OPID { get; set; }
        public Nullable<int> TRFID { get; set; }
        public Nullable<int> ENTITYID { get; set; }
        public Nullable<int> ENTITYTYPE { get; set; }
        public Nullable<int> TIRPAYEUR { get; set; }
        public Nullable<int> TIRFACTURE { get; set; }
        public Nullable<int> ADRFID { get; set; }
        public Nullable<int> ADRLID { get; set; }
        public Nullable<int> DEPID { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public Nullable<int> RGMID { get; set; }
        public Nullable<int> TVATID { get; set; }
        public Nullable<int> INTERSITES { get; set; }
        public Nullable<int> DEVID { get; set; }
        public Nullable<decimal> DOCCOLISAGE { get; set; }
        public Nullable<int> CAMID { get; set; }
        public Nullable<int> VSTID { get; set; }
        public Nullable<int> TRNID { get; set; }
        public Nullable<decimal> DOCMNTHTBRUT { get; set; }
        public Nullable<decimal> DOCMNTREML { get; set; }
        public Nullable<decimal> DOCMNTG { get; set; }
        public Nullable<decimal> DOCMNTRETOUR { get; set; }
        public Nullable<decimal> DOCESCOMPTE { get; set; }
        public Nullable<decimal> DOCMNTESCOMPTE { get; set; }
        public Nullable<decimal> DOCMNTREMP { get; set; }
        public Nullable<decimal> DLPU { get; set; }
        public Nullable<int> DLPUISTTC { get; set; }
        public Nullable<decimal> DLPUHTBRUT { get; set; }
        public Nullable<decimal> DLPUTTC { get; set; }
        public Nullable<decimal> DLPUHTNET { get; set; }
        public int DISTRIBUTEUR { get; set; }
    }
}
